---
apiVersion: v1
kind: Service
metadata:
  name: basic-auth
  #namespace: ambassador
spec:
  type: ClusterIP
  clusterIP: None
  selector:
    app: basic-auth
  ports:
  - port: 3000
    name: http-basic-auth
    targetPort: http-api
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: basic-auth
  #namespace: ambassador
  labels:
    app: basic-auth
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: basic-auth
    spec:
      containers:
      - name: basic-auth
        image: datawire/ambassador-auth-service:1.1.1
        imagePullPolicy: Always
        ports:
        - name: http-api
          containerPort: 3000
        resources:
          limits:
            cpu: "0.1"
            memory: 100Mi
          requests:
            cpu: "0.1"
            memory: 100Mi
        livenessProbe:
          httpGet:
            path: /healthcheck
            port: 3000
            scheme: HTTP
            initialDelaySeconds: 30
            timeoutSeconds: 1
            periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /healthcheck
            port: 3000
            scheme: HTTP
            initialDelaySeconds: 30
            imeoutSeconds: 1
            periodSeconds: 10
        env:
          - name: MY_NODE_NAME
            valueFrom:
              fieldRef:
                fieldPath: spec.nodeName
          - name: MY_POD_NAME
            valueFrom:
              fieldRef:
                fieldPath: metadata.name
          - name: MY_POD_NAMESPACE
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace
          - name: MY_POD_IP
            valueFrom:
              fieldRef:
                fieldPath: status.podIP
          - name: MY_POD_SERVICE_ACCOUNT
            valueFrom:
              fieldRef:
                fieldPath: spec.serviceAccountName
          - name: PORT
            value: '3000'
          - name: NODE_ENV
            value: production
          - name: AUTH_PASSWORD
            valueFrom:
              secretKeyRef:
                name: basic-auth-secret
                key: password
          #- name: AUTH_PATH
          #  value: '/extauth/backend/get-quote'
